#!/usr/bin/env python3
"""
Vendor company logos for The Range into the repository.

Why this exists
---------------
The Range renders a logo tile for every company. Resolving those marks at
runtime from third-party favicon APIs is unreliable in the real world: those
endpoints are a standard entry on ad- and tracker-blocklists, so a chain built
only from them renders monograms for a large share of visitors while looking
perfectly healthy in a clean browser. Marks committed to the repository cannot
be blocked, rate-limited, or retired.

Run this on a machine with normal internet access:

    python3 scripts/fetch-logos.py              # fetch marks that are missing
    python3 scripts/fetch-logos.py --limit 50   # first 50 only (quick trial)
    python3 scripts/fetch-logos.py --force      # re-fetch even if present

It writes:
    prototype/assets/logos/<brand-domain>.<ext>   the marks themselves
    prototype/data/range/logo-overrides.js        the domain -> path map

The map is loaded before js/logo.js and takes priority over every network
source, so any company with a vendored mark renders it immediately, offline,
and identically for every visitor. Companies without one keep the existing
resolver chain and, failing that, the designed monogram tile.

Only the company's own domain is contacted (apple-touch-icon, then favicon):
these are the site's own published icons, fetched one at a time, and the marks
remain the trademarks of their owners — shown nominatively next to the company
they identify, exactly as the runtime chain does.
"""

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB = os.path.join(ROOT, 'prototype', 'data', 'range', 'companies-db.js')
GRAPH = os.path.join(ROOT, 'prototype', 'data', 'range', 'graph.js')
OPPS = os.path.join(ROOT, 'prototype', 'data', 'range', 'opportunities.js')
OUT_DIR = os.path.join(ROOT, 'prototype', 'assets', 'logos')
OUT_MAP = os.path.join(ROOT, 'prototype', 'data', 'range', 'logo-overrides.js')

UA = 'Mozilla/5.0 (compatible; MetanoiaLabs-logo-fetch/1.0; +https://labsmetanoia.github.io/)'
SUFFIX2 = re.compile(r'\.(co|com|net|org|gov|ac|edu|or|go)\.[a-z]{2}$')
# Kept identical to the runtime chain in js/logo.js.
PATHS = ['/apple-touch-icon.png', '/apple-touch-icon-precomposed.png', '/favicon.ico']
EXT_BY_TYPE = {
    'image/png': '.png', 'image/x-icon': '.ico', 'image/vnd.microsoft.icon': '.ico',
    'image/jpeg': '.jpg', 'image/svg+xml': '.svg', 'image/webp': '.webp', 'image/gif': '.gif',
}


def brand_domain(raw):
    """Root brand domain — mirrors brandDomain() in js/logo.js."""
    d = re.sub(r'^https?://', '', str(raw or '')).split('/')[0].split(':')[0].lower()
    if not d:
        return ''
    keep = 3 if SUFFIX2.search(d) else 2
    parts = d.split('.')
    return '.'.join(parts[-keep:]) if len(parts) > keep else d


def domains():
    """Every brand domain referenced by the product, de-duplicated, in order."""
    found, seen = [], set()

    def add(dom):
        d = brand_domain(dom)
        if d and d not in seen:
            seen.add(d)
            found.append(d)

    for path, pattern in (
        (DB, r'"([a-z0-9.\-]+\.[a-z]{2,})"'),
        (GRAPH, r'"website":\s*"([^"]+)"'),
        (OPPS, r"website:\s*'([^']+)'"),
    ):
        if not os.path.exists(path):
            continue
        with open(path, encoding='utf-8') as fh:
            text = fh.read()
        for match in re.findall(pattern, text):
            add(match)
    return found


def fetch(url, timeout=12):
    req = urllib.request.Request(url, headers={'User-Agent': UA, 'Accept': 'image/*,*/*'})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        ctype = (resp.headers.get('Content-Type') or '').split(';')[0].strip().lower()
        return resp.read(), ctype


def existing(dom):
    for ext in ('.png', '.ico', '.svg', '.jpg', '.webp', '.gif'):
        path = os.path.join(OUT_DIR, dom + ext)
        if os.path.exists(path):
            return dom + ext
    return None


def write_map(entries):
    lines = [
        '/* Vendored company marks for The Range — generated by scripts/fetch-logos.py.',
        ' * Loaded before js/logo.js; these take priority over every network source,',
        ' * so a vendored company renders instantly, offline, and identically for all',
        ' * visitors. Do not edit by hand — re-run the script instead.',
        ' *',
        ' * Marks are the trademarks of their respective owners, shown nominatively',
        ' * next to the company they identify. %d vendored.' % len(entries),
        ' */',
        'window.MT_LOGO_OVERRIDES = {',
    ]
    for dom in sorted(entries):
        lines.append("  %s: %s," % (json.dumps(dom), json.dumps('../../assets/logos/' + entries[dom])))
    lines.append('};')
    lines.append('')
    with open(OUT_MAP, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(lines))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--limit', type=int, default=0, help='stop after N companies')
    ap.add_argument('--force', action='store_true', help='re-fetch marks already on disk')
    ap.add_argument('--min-bytes', type=int, default=180, help='reject responses smaller than this')
    args = ap.parse_args()

    os.makedirs(OUT_DIR, exist_ok=True)
    doms = domains()
    if args.limit:
        doms = doms[:args.limit]
    print('%d brand domains referenced by the product' % len(doms))

    entries, got, kept, missed = {}, 0, 0, []
    for i, dom in enumerate(doms, 1):
        have = existing(dom)
        if have and not args.force:
            entries[dom] = have
            kept += 1
            continue
        saved = None
        for path in PATHS:
            try:
                blob, ctype = fetch('https://' + dom + path)
            except (urllib.error.URLError, urllib.error.HTTPError, OSError, ValueError):
                continue
            if len(blob) < args.min_bytes:
                continue          # 1×1 spacers and empty 200s
            ext = EXT_BY_TYPE.get(ctype) or os.path.splitext(path)[1]
            name = dom + ext
            with open(os.path.join(OUT_DIR, name), 'wb') as fh:
                fh.write(blob)
            saved = name
            break
        if saved:
            entries[dom] = saved
            got += 1
            print('  [%d/%d] %-34s %s' % (i, len(doms), dom, saved))
        else:
            missed.append(dom)
            print('  [%d/%d] %-34s no icon found — resolver chain will handle it' % (i, len(doms), dom))

    write_map(entries)
    print('\nfetched %d · already present %d · not found %d' % (got, kept, len(missed)))
    print('wrote %s (%d entries)' % (os.path.relpath(OUT_MAP, ROOT), len(entries)))
    if missed:
        print('no icon at a predictable path (runtime chain still tries the APIs):')
        print('  ' + ', '.join(missed[:12]) + (' …' if len(missed) > 12 else ''))
    print('\nCommit prototype/assets/logos/ and prototype/data/range/logo-overrides.js '
          'to make these marks permanent.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
