#!/usr/bin/env python3
"""
Render the supplied product-overview PDFs to page images for the in-product
slide viewer (prototype/products/the-map/js/map-overview.js).

The PDFs are the source of truth and are served unchanged; the images are a
faithful 2x rendering of each page so the document can be presented as a
native slideshow on every device — including mobile browsers that cannot
display PDFs inline. Re-run this whenever a PDF is replaced.

Usage:  python3 scripts/render-overview-pages.py
Requires: pymupdf  (pip install pymupdf)
"""
import json
import os
import sys

try:
    import pymupdf
except ImportError:
    sys.exit('pymupdf is required: pip install pymupdf')

ROOT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'prototype')
OUT = os.path.join(ROOT, 'assets', 'docs', 'the-map-overview')
DOCS = {'en': 'the-map-overview-en.pdf', 'id': 'the-map-overview-id.pdf'}
SCALE = 2          # 960x540 source → 1920x1080
JPG_QUALITY = 86


def main():
    pages = {}
    for lang, fn in DOCS.items():
        doc = pymupdf.open(os.path.join(ROOT, 'assets', 'docs', fn))
        d = os.path.join(OUT, lang)
        os.makedirs(d, exist_ok=True)
        pages[lang] = []
        for i, page in enumerate(doc):
            pix = page.get_pixmap(matrix=pymupdf.Matrix(SCALE, SCALE), alpha=False)
            name = 'p%02d.jpg' % (i + 1)
            pix.save(os.path.join(d, name), jpg_quality=JPG_QUALITY)
            pages[lang].append({'src': '../../assets/docs/the-map-overview/%s/%s' % (lang, name),
                                'w': pix.width, 'h': pix.height})
            print('%s %s %dx%d' % (lang, name, pix.width, pix.height))
    with open(os.path.join(OUT, 'pages.js'), 'w', encoding='utf-8') as f:
        f.write('/* Rendered pages of the supplied product-overview documents '
                '(assets/docs/the-map-overview-*.pdf),\n   generated by '
                'scripts/render-overview-pages.py. Regenerate when the PDFs change. */\n')
        f.write('window.MT_MAP_OVERVIEW_PAGES = ' + json.dumps(pages, indent=1) + ';\n')
    print('wrote pages.js')


if __name__ == '__main__':
    main()
